
[TF_Setting]
TF_Data_Path=D:/Project/ThroughFocus/ThroughFocus/R24050801_Opposfr.txt

Item_Select=27

Center_H=32
Center_V=32
3F_Dia_H=32
3F_Dia_V=32
3F_LR_H=32
3F_LR_V=32
5F_Dia_H=20
5F_Dia_V=20
6F_Dia_H=0
6F_Dia_V=0
7F_Dia_H=17
7F_Dia_V=17
8F_Dia_H=17
8F_Dia_V=17
9F_Dia_H=0
9F_Dia_V=0

;; X=0 , 十=1, 米=2 , LR = 3, UD =4
2F_Pos=3  
3F_Pos=0
4F_Pos=0
5F_Pos=0
6F_Pos=0
7F_Pos=0
8F_Pos=0
9F_Pos=0

PD_Spec3=70
PD_Spec_H3=100
PD_Spec_V3=100

PD_Spec5=70
PD_Spec_H5=100
PD_Spec_V5=100

PD_Spec6=70
PD_Spec_H6=100
PD_Spec_V6=100

PD_Spec7=70
PD_Spec_H7=100
PD_Spec_V7=100

PD_Spec8=70
PD_Spec_H8=100
PD_Spec_V8=100

PS_Spec3=70
PS_Spec_H3=100
PS_Spec_V3=100

PS_Spec5=70
PS_Spec_H5=100
PS_Spec_V5=100

PS_Spec6=70
PS_Spec_H6=100
PS_Spec_V6=100

PS_Spec7=70
PS_Spec_H7=100
PS_Spec_V7=100

PS_Spec8=70
PS_Spec_H8=100
PS_Spec_V8=100

OK_Range_Spec=12
HVD_Spec=30

TF_step=31

SFR_Data_1=11
SFR_Data_2=12
SFR_Data_3=31
SFR_Data_4=32
SFR_Data_5=33
SFR_Data_6=34
SFR_Data_7=23
SFR_Data_8=24
SFR_Data_9=37
SFR_Data_10=38
SFR_Data_11=35
SFR_Data_12=36
SFR_Data_13=21
SFR_Data_14=22
SFR_Data_15=51
SFR_Data_16=52
SFR_Data_17=53
SFR_Data_18=54
SFR_Data_19=57
SFR_Data_20=58
SFR_Data_21=55
SFR_Data_22=56
SFR_Data_23=71
SFR_Data_24=72
SFR_Data_25=73
SFR_Data_26=74
SFR_Data_27=77
SFR_Data_28=78
SFR_Data_29=75
SFR_Data_30=76
SFR_Data_31=81
SFR_Data_32=82
SFR_Data_33=83
SFR_Data_34=84
SFR_Data_35=87
SFR_Data_36=88
SFR_Data_37=85
SFR_Data_38=86
SFR_Data_39=0
SFR_Data_40=0
SFR_Data_41=0
SFR_Data_42=0
SFR_Data_43=0
SFR_Data_44=0
SFR_Data_45=0
SFR_Data_46=0
SFR_Data_47=0
SFR_Data_48=0
SFR_Data_49=0
SFR_Data_50=0

